### ISSUE TITLE
Health check based on content presence in Virtuoso causing deployment issues in test environment

### ISSUE THREAD

**Issue by FrankMaverick** [teamdigitale/dati-semantic-lodview#89]
When checking https://github.com/teamdigitale/dati-semantic-kubernetes/blob/test/dati-semantic-lodview/deploymentConfig.yaml, we see that for the following properties, a check is made on /onto/CPV, which refers to the contents of Virtuoso:

```
readinessProbe: 
            httpGet:
              path: /onto/CPV
              port: 8080
              scheme: HTTP
livenessProbe: # FIXME
            httpGet:
              path: /onto/CPV
              port: 8080
              scheme: HTTP_
```

Essentially, if /onto/CPV is not present in Virtuoso, OpenShift does not consider the pod as "ready".
